CREATE TABLE `profile_personal` (
  `profile_id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(11) NOT NULL,
  `first_name` varchar(50) NOT NULL,
  `last_name` varchar(50) NOT NULL,
  `middle_name` varchar(50) DEFAULT NULL,
  `prefix` varchar(10) DEFAULT NULL,
  `suffix` varchar(10) DEFAULT NULL,
  `gender` tinyint(4) NOT NULL COMMENT '1=Male, 2=Female, 3=Other',
  `birth_date` date NOT NULL,
  `phone_mobile` varchar(20) NOT NULL,
  `phone_home` varchar(20) DEFAULT NULL,
  `phone_emergency` varchar(20) DEFAULT NULL,
  `email_id` varchar(100) NOT NULL,
  `marital_status` tinyint(4) NOT NULL,
  `religion` tinyint(4) DEFAULT NULL,
  `nationality` tinyint(4) DEFAULT NULL,
  `caste` tinyint(4) DEFAULT NULL,
  `height_inches` decimal(5,2) DEFAULT NULL,
  `height_cms` decimal(5,2) DEFAULT NULL,
  `weight` decimal(5,2) DEFAULT NULL,
  `weight_units` varchar(10) DEFAULT NULL COMMENT 'kg, lbs',
  `complexion` tinyint(4) DEFAULT NULL,
  `linkedin` varchar(255) DEFAULT NULL,
  `facebook` varchar(255) DEFAULT NULL,
  `instagram` varchar(255) DEFAULT NULL,
  `whatsapp_number` varchar(20) DEFAULT NULL,
  `profession` tinyint(4) DEFAULT NULL,
  `disability` tinyint(4) DEFAULT NULL,
  `created_user` varchar(100) NOT NULL,
  `created_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `is_active` tinyint(4) DEFAULT 1,
  PRIMARY KEY (`profile_id`),
  KEY `idx_profile_personal_email` (`email_id`),
  KEY `idx_profile_personal_active` (`is_active`)
) ENGINE=InnoDB;
