CREATE TABLE IF NOT EXISTS stripe_prices (
    id VARCHAR(255) PRIMARY KEY COMMENT 'Stripe price ID (e.g., price_XXX)',
    product_id VARCHAR(255) NOT NULL COMMENT 'Associated Stripe product ID',
    active BOOLEAN DEFAULT TRUE COMMENT 'Whether the price is active',
    currency VARCHAR(3) NOT NULL COMMENT 'Three-letter ISO currency code',
    unit_amount BIGINT NOT NULL COMMENT 'Amount in smallest currency unit (e.g., cents)',
    nickname VARCHAR(255) COMMENT 'Price nickname',
    type ENUM('one_time', 'recurring') NOT NULL COMMENT 'Price type',
    recurring_interval ENUM('day', 'week', 'month', 'year') COMMENT 'Billing interval',
    recurring_interval_count INT COMMENT 'Number of intervals between billings',
    recurring_usage_type ENUM('metered', 'licensed') COMMENT 'Usage type if recurring',
    billing_scheme ENUM('per_unit', 'tiered') DEFAULT 'per_unit' COMMENT 'Billing scheme',
    tax_behavior ENUM('inclusive', 'exclusive', 'unspecified') DEFAULT 'unspecified' COMMENT 'Tax behavior',
    tiers JSON COMMENT 'Price tiers for tiered pricing',
    metadata JSON COMMENT 'Additional price metadata',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record update timestamp',
    deleted_at TIMESTAMP NULL COMMENT 'Soft delete timestamp',
    INDEX idx_product_id (product_id),
    INDEX idx_active (active),
    INDEX idx_type (type),
    INDEX idx_currency (currency),
    INDEX idx_created_at (created_at),
    CONSTRAINT fk_stripe_prices_product FOREIGN KEY (product_id) REFERENCES stripe_products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Stripe prices data';
