CREATE TABLE IF NOT EXISTS stripe_payment_methods (
    id VARCHAR(255) PRIMARY KEY COMMENT 'Stripe payment method ID (e.g., pm_XXX)',
    customer_id VARCHAR(255) NOT NULL COMMENT 'Associated Stripe customer ID',
    type ENUM('card', 'bank_account', 'alipay', 'au_becs_debit', 'bacs_debit', 'bancontact', 'eps', 'giropay', 'ideal', 'p24', 'sepa_debit', 'sofort', 'wechat_pay') NOT NULL COMMENT 'Payment method type',
    billing_details_name VARCHAR(255) COMMENT 'Billing name',
    billing_details_email VARCHAR(255) COMMENT 'Billing email',
    billing_details_phone VARCHAR(50) COMMENT 'Billing phone',
    billing_details_address_line1 VARCHAR(255) COMMENT 'Billing address line 1',
    billing_details_address_line2 VARCHAR(255) COMMENT 'Billing address line 2',
    billing_details_address_city VARCHAR(255) COMMENT 'Billing city',
    billing_details_address_state VARCHAR(255) COMMENT 'Billing state/province',
    billing_details_address_postal_code VARCHAR(20) COMMENT 'Billing postal/ZIP code',
    billing_details_address_country VARCHAR(2) COMMENT 'Billing country code (ISO 3166-1 alpha-2)',
    card_brand VARCHAR(50) COMMENT 'Card brand (Visa, Mastercard, etc.)',
    card_last4 VARCHAR(4) COMMENT 'Last 4 digits of card',
    card_exp_month TINYINT COMMENT 'Card expiration month',
    card_exp_year SMALLINT COMMENT 'Card expiration year',
    card_funding VARCHAR(20) COMMENT 'Card funding type (credit, debit, prepaid, unknown)',
    card_country VARCHAR(2) COMMENT 'Card country code',
    is_default BOOLEAN DEFAULT FALSE COMMENT 'Whether this is the default payment method',
    metadata JSON COMMENT 'Additional payment method metadata',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record update timestamp',
    deleted_at TIMESTAMP NULL COMMENT 'Soft delete timestamp',
    INDEX idx_customer_id (customer_id),
    INDEX idx_type (type),
    INDEX idx_card_brand (card_brand),
    INDEX idx_created_at (created_at),
    CONSTRAINT fk_stripe_payment_methods_customer FOREIGN KEY (customer_id) REFERENCES stripe_customers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Stripe payment methods data';
