CREATE TABLE IF NOT EXISTS stripe_subscriptions (
    id VARCHAR(255) PRIMARY KEY COMMENT 'Stripe subscription ID (e.g., sub_XXX)',
    customer_id VARCHAR(255) NOT NULL COMMENT 'Associated Stripe customer ID',
    status ENUM('incomplete', 'incomplete_expired', 'trialing', 'active', 'past_due', 'canceled', 'unpaid') NOT NULL COMMENT 'Subscription status',
    price_id VARCHAR(255) NOT NULL COMMENT 'Associated Stripe price ID',
    quantity INT DEFAULT 1 COMMENT 'Quantity of the plan',
    cancel_at_period_end BOOLEAN DEFAULT FALSE COMMENT 'Whether to cancel at the end of the period',
    current_period_start TIMESTAMP NULL COMMENT 'Start of the current period',
    current_period_end TIMESTAMP NULL COMMENT 'End of the current period',
    start_date TIMESTAMP NULL COMMENT 'Start date of the subscription',
    ended_at TIMESTAMP NULL COMMENT 'End date if subscription ended',
    cancel_at TIMESTAMP NULL COMMENT 'Scheduled cancellation date',
    canceled_at TIMESTAMP NULL COMMENT 'Date when subscription was canceled',
    trial_start TIMESTAMP NULL COMMENT 'Trial period start date',
    trial_end TIMESTAMP NULL COMMENT 'Trial period end date',
    application_fee_percent DECIMAL(5,2) COMMENT 'Application fee percentage',
    default_payment_method_id VARCHAR(255) COMMENT 'Default payment method for this subscription',
    latest_invoice_id VARCHAR(255) COMMENT 'Latest invoice ID',
    collection_method ENUM('charge_automatically', 'send_invoice') DEFAULT 'charge_automatically' COMMENT 'Collection method',
    days_until_due INT COMMENT 'Days until due if collection method is send_invoice',
    metadata JSON COMMENT 'Additional subscription metadata',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record update timestamp',
    deleted_at TIMESTAMP NULL COMMENT 'Soft delete timestamp',
    INDEX idx_customer_id (customer_id),
    INDEX idx_price_id (price_id),
    INDEX idx_status (status),
    INDEX idx_current_period_end (current_period_end),
    INDEX idx_created_at (created_at),
    CONSTRAINT fk_stripe_subscriptions_customer FOREIGN KEY (customer_id) REFERENCES stripe_customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_stripe_subscriptions_price FOREIGN KEY (price_id) REFERENCES stripe_prices(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Stripe subscriptions data';
