CREATE TABLE IF NOT EXISTS stripe_invoices (
    id VARCHAR(255) PRIMARY KEY COMMENT 'Stripe invoice ID (e.g., in_XXX)',
    customer_id VARCHAR(255) NOT NULL COMMENT 'Associated Stripe customer ID',
    subscription_id VARCHAR(255) COMMENT 'Associated Stripe subscription ID',
    status ENUM('draft', 'open', 'paid', 'uncollectible', 'void') NOT NULL COMMENT 'Invoice status',
    currency VARCHAR(3) NOT NULL COMMENT 'Three-letter ISO currency code',
    total BIGINT NOT NULL COMMENT 'Total amount in smallest currency unit (e.g., cents)',
    subtotal BIGINT NOT NULL COMMENT 'Subtotal amount',
    tax BIGINT DEFAULT 0 COMMENT 'Tax amount',
    amount_due BIGINT NOT NULL COMMENT 'Amount due',
    amount_paid BIGINT DEFAULT 0 COMMENT 'Amount paid',
    amount_remaining BIGINT DEFAULT 0 COMMENT 'Amount remaining',
    invoice_number VARCHAR(255) COMMENT 'Invoice number',
    invoice_pdf VARCHAR(2048) COMMENT 'URL to the invoice PDF',
    billing_reason VARCHAR(50) COMMENT 'Reason for invoice creation',
    period_start TIMESTAMP NULL COMMENT 'Start of billing period',
    period_end TIMESTAMP NULL COMMENT 'End of billing period',
    due_date TIMESTAMP NULL COMMENT 'Due date for payment',
    paid_at TIMESTAMP NULL COMMENT 'When the invoice was paid',
    auto_advance BOOLEAN DEFAULT TRUE COMMENT 'Whether auto-advance is enabled',
    collection_method ENUM('charge_automatically', 'send_invoice') DEFAULT 'charge_automatically' COMMENT 'Collection method',
    attempt_count INT DEFAULT 0 COMMENT 'Number of payment attempts',
    next_payment_attempt TIMESTAMP NULL COMMENT 'Next scheduled payment attempt',
    metadata JSON COMMENT 'Additional invoice metadata',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record update timestamp',
    deleted_at TIMESTAMP NULL COMMENT 'Soft delete timestamp',
    INDEX idx_customer_id (customer_id),
    INDEX idx_subscription_id (subscription_id),
    INDEX idx_status (status),
    INDEX idx_due_date (due_date),
    INDEX idx_created_at (created_at),
    CONSTRAINT fk_stripe_invoices_customer FOREIGN KEY (customer_id) REFERENCES stripe_customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_stripe_invoices_subscription FOREIGN KEY (subscription_id) REFERENCES stripe_subscriptions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Stripe invoices data';
