CREATE TABLE IF NOT EXISTS stripe_payment_intents (
    id VARCHAR(255) PRIMARY KEY COMMENT 'Stripe payment intent ID (e.g., pi_XXX)',
    customer_id VARCHAR(255) COMMENT 'Associated Stripe customer ID',
    amount BIGINT NOT NULL COMMENT 'Amount in smallest currency unit (e.g., cents)',
    currency VARCHAR(3) NOT NULL COMMENT 'Three-letter ISO currency code',
    payment_method_id VARCHAR(255) COMMENT 'Payment method used for this payment intent',
    status ENUM('requires_payment_method', 'requires_confirmation', 'requires_action', 'processing', 'requires_capture', 'canceled', 'succeeded') NOT NULL COMMENT 'Payment intent status',
    setup_future_usage ENUM('on_session', 'off_session') COMMENT 'Setup future usage',
    capture_method ENUM('automatic', 'manual') DEFAULT 'automatic' COMMENT 'Capture method',
    confirmation_method ENUM('automatic', 'manual') DEFAULT 'automatic' COMMENT 'Confirmation method',
    description TEXT COMMENT 'Description of the payment',
    receipt_email VARCHAR(255) COMMENT 'Email for receipt',
    statement_descriptor VARCHAR(22) COMMENT 'Statement descriptor',
    statement_descriptor_suffix VARCHAR(22) COMMENT 'Statement descriptor suffix',
    next_action JSON COMMENT 'Next action required',
    last_payment_error JSON COMMENT 'Last payment error details',
    invoice_id VARCHAR(255) COMMENT 'Associated invoice ID',
    canceled_at TIMESTAMP NULL COMMENT 'Cancellation timestamp',
    cancellation_reason VARCHAR(255) COMMENT 'Reason for cancellation',
    metadata JSON COMMENT 'Additional payment intent metadata',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record update timestamp',
    deleted_at TIMESTAMP NULL COMMENT 'Soft delete timestamp',
    INDEX idx_customer_id (customer_id),
    INDEX idx_payment_method_id (payment_method_id),
    INDEX idx_status (status),
    INDEX idx_invoice_id (invoice_id),
    INDEX idx_created_at (created_at),
    CONSTRAINT fk_stripe_payment_intents_customer FOREIGN KEY (customer_id) REFERENCES stripe_customers(id) ON DELETE SET NULL,
    CONSTRAINT fk_stripe_payment_intents_invoice FOREIGN KEY (invoice_id) REFERENCES stripe_invoices(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Stripe payment intents data';
