CREATE TABLE IF NOT EXISTS stripe_charges (
    id VARCHAR(255) PRIMARY KEY COMMENT 'Stripe charge ID (e.g., ch_XXX)',
    customer_id VARCHAR(255) COMMENT 'Associated Stripe customer ID',
    payment_intent_id VARCHAR(255) COMMENT 'Associated payment intent ID',
    invoice_id VARCHAR(255) COMMENT 'Associated invoice ID',
    payment_method_id VARCHAR(255) COMMENT 'Payment method used for this charge',
    amount BIGINT NOT NULL COMMENT 'Amount in smallest currency unit (e.g., cents)',
    amount_refunded BIGINT DEFAULT 0 COMMENT 'Amount refunded',
    currency VARCHAR(3) NOT NULL COMMENT 'Three-letter ISO currency code',
    status ENUM('succeeded', 'pending', 'failed') NOT NULL COMMENT 'Charge status',
    captured BOOLEAN DEFAULT TRUE COMMENT 'Whether the charge has been captured',
    paid BOOLEAN DEFAULT FALSE COMMENT 'Whether the charge has been paid',
    refunded BOOLEAN DEFAULT FALSE COMMENT 'Whether the charge has been refunded',
    disputed BOOLEAN DEFAULT FALSE COMMENT 'Whether the charge has been disputed',
    failure_code VARCHAR(100) COMMENT 'Failure code if charge failed',
    failure_message TEXT COMMENT 'Failure message if charge failed',
    receipt_email VARCHAR(255) COMMENT 'Email for receipt',
    receipt_number VARCHAR(255) COMMENT 'Receipt number',
    receipt_url VARCHAR(2048) COMMENT 'URL to the receipt',
    description TEXT COMMENT 'Description of the charge',
    statement_descriptor VARCHAR(22) COMMENT 'Statement descriptor',
    statement_descriptor_suffix VARCHAR(22) COMMENT 'Statement descriptor suffix',
    metadata JSON COMMENT 'Additional charge metadata',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record update timestamp',
    deleted_at TIMESTAMP NULL COMMENT 'Soft delete timestamp',
    INDEX idx_customer_id (customer_id),
    INDEX idx_payment_intent_id (payment_intent_id),
    INDEX idx_invoice_id (invoice_id),
    INDEX idx_payment_method_id (payment_method_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    CONSTRAINT fk_stripe_charges_customer FOREIGN KEY (customer_id) REFERENCES stripe_customers(id) ON DELETE SET NULL,
    CONSTRAINT fk_stripe_charges_payment_intent FOREIGN KEY (payment_intent_id) REFERENCES stripe_payment_intents(id) ON DELETE SET NULL,
    CONSTRAINT fk_stripe_charges_invoice FOREIGN KEY (invoice_id) REFERENCES stripe_invoices(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Stripe charges data';
