CREATE TABLE IF NOT EXISTS stripe_balance_transactions (
    id VARCHAR(255) PRIMARY KEY COMMENT 'Stripe balance transaction ID (e.g., txn_XXX)',
    amount BIGINT NOT NULL COMMENT 'Amount in smallest currency unit (e.g., cents)',
    currency VARCHAR(3) NOT NULL COMMENT 'Three-letter ISO currency code',
    net BIGINT NOT NULL COMMENT 'Net amount after fees',
    fee BIGINT NOT NULL DEFAULT 0 COMMENT 'Fee amount',
    fee_details JSON COMMENT 'Detailed breakdown of fees',
    type ENUM('charge', 'refund', 'adjustment', 'application_fee', 'application_fee_refund', 'transfer', 'transfer_refund', 'payout', 'payout_cancel', 'payout_failure', 'stripe_fee', 'network_cost', 'payment', 'payment_refund', 'payment_reversal') NOT NULL COMMENT 'Transaction type',
    source_id VARCHAR(255) COMMENT 'ID of the source object',
    source_type VARCHAR(50) COMMENT 'Type of the source object',
    description TEXT COMMENT 'Description of the transaction',
    status ENUM('available', 'pending') NOT NULL DEFAULT 'pending' COMMENT 'Transaction status',
    available_on TIMESTAMP NULL COMMENT 'When funds become available',
    exchange_rate DECIMAL(10,6) COMMENT 'Exchange rate if currency conversion was performed',
    reporting_category VARCHAR(50) COMMENT 'Reporting category for the transaction',
    metadata JSON COMMENT 'Additional transaction metadata',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation timestamp',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Record update timestamp',
    deleted_at TIMESTAMP NULL COMMENT 'Soft delete timestamp',
    INDEX idx_type (type),
    INDEX idx_source_id (source_id),
    INDEX idx_status (status),
    INDEX idx_available_on (available_on),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Stripe balance transactions data';
